package com.rms.restaurant.common.utils.enums;

/** Manual vouchers (CashFlowModal) only ever assign EMPLOYEE/OTHER; CUSTOMER is reserved
 * for receipts auto-generated by {@code createSystemVoucher} when an invoice gets paid. */
public enum CashbookPartnerGroup {
    EMPLOYEE,
    CUSTOMER,
    OTHER
}
