package com.rms.restaurant.common.utils.enums;

/** How a cashbook voucher came to exist — MANUAL via CashFlowModal, or auto-generated by
 * another module (PAYROLL salary payout, INVOICE_PAYMENT paid invoice). */
public enum CashbookSourceType {
    MANUAL,
    PAYROLL,
    INVOICE_PAYMENT
}
